import { Navbar } from '../../components/shared/navbar';
import { Footer } from '../../components/shared/footer';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/tabs';

export const metadata = {
  title: 'Legal & Compliance | Finrena',
};

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-zinc-950 flex flex-col text-zinc-100 overflow-x-hidden relative">
      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto px-6 py-20 relative z-10">
        <div className="mb-12">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-3">Legal & Compliance Hub</h1>
          <p className="text-zinc-400">Institutional disclosures, terms of service, and privacy policies.</p>
        </div>

        <Tabs defaultValue="terms" className="w-full">
          <TabsList className="mb-8 bg-zinc-900 border border-zinc-800 p-1">
            <TabsTrigger value="terms" className="data-[state=active]:bg-zinc-800 data-[state=active]:text-zinc-100 text-zinc-400">
              Terms of Service
            </TabsTrigger>
            <TabsTrigger value="privacy" className="data-[state=active]:bg-zinc-800 data-[state=active]:text-zinc-100 text-zinc-400">
              Privacy Policy
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="terms" className="focus-visible:outline-none">
            <div className="prose prose-invert prose-zinc max-w-none prose-headings:text-zinc-100 prose-a:text-emerald-400 hover:prose-a:text-emerald-300 bg-zinc-900/40 border border-zinc-800/80 rounded-xl p-8 md:p-10">
              <h2 className="mt-0">Terms of Service</h2>
              <p className="text-sm font-mono text-zinc-500 mb-8 mt-[-0.5rem] italic">Last Updated: October 2026</p>

              <h3>1. Acceptance of Terms</h3>
              <p>
                By accessing and using Finrena (the "Platform"), developed by Softage Labs, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.
              </p>

              <h3>2. Enterprise Research Environment & Disclaimer of Financial Advice</h3>
              <p>
                Finrena is a quantitative research environment and decision-support terminal. It is not a registered investment advisor, broker, or fiduciary. All outputs, analytics, and adversarial stress-tests generated by the Platform are for research and data-synthesis purposes only. The Platform does not recommend the purchase or sale of any specific asset or security.
              </p>

              <h3>3. System Architecture & Limitation of Liability</h3>
              <p>The Platform operates on a bifurcated architecture:</p>
              <ul>
                <li><strong>The Deterministic Math Engine (The Quant):</strong> Executes mathematical functions (e.g., Monte Carlo simulations) based on historical data. While mathematically precise, historical data does not predict future performance.</li>
                <li><strong>The Heuristic Synthesizers (LLM Agents):</strong> The natural language models utilized for fundamental and forensic analysis can and will hallucinate, misinterpret financial filings, and output false narratives.</li>
              </ul>
              <p>
                The user assumes 100% of the risk when interpreting the Platform's outputs. Softage Labs holds zero liability for any trading losses, capital destruction, or misinformed financial decisions made based on the usage of this software.
              </p>

              <h3>4. No Fiduciary Duty</h3>
              <p>
                Softage Labs explicitly waives any and all fiduciary responsibility. We are software engineers providing a technical interface, not financial professionals. You must conduct your own independent due diligence and consult with a licensed financial professional before making any investment decisions.
              </p>

              <h3>5. Institutional Access & Fair Use</h3>
              <p>
                Access to the Platform's live computational endpoints is provided "as-is". We reserve the right to throttle, rate-limit, or terminate access for automated scraping or abusive query volumes that degrade the computational experience for other users.
              </p>
            </div>
          </TabsContent>
          
          <TabsContent value="privacy" className="focus-visible:outline-none">
            <div className="prose prose-invert prose-zinc max-w-none prose-headings:text-zinc-100 prose-a:text-emerald-400 hover:prose-a:text-emerald-300 bg-zinc-900/40 border border-zinc-800/80 rounded-xl p-8 md:p-10">
              <h2 className="mt-0">Privacy Policy</h2>
              <p className="text-sm font-mono text-zinc-500 mb-8 mt-[-0.5rem] italic">Last Updated: October 2026</p>

              <h3>1. Data Collection & OAuth Scopes</h3>
              <p>
                When you authenticate using third-party providers (such as Google or GitHub), Softage Labs only requests the absolute minimum required scopes: your email address and basic profile information. This data is used purely for authentication and session management. We do not request access to your repositories, drive files, or contacts.
              </p>

              <h3>2. Strict Cookie Usage & Session Security</h3>
              <p>
                Finrena utilizes a highly secure, dual-token architecture to manage your session. Both Access Tokens and Refresh Tokens are dispatched via <code>Set-Cookie</code> headers configured with <code>HttpOnly</code> and <code>SameSite=Lax</code>. This ensures that your session tokens are completely inaccessible to JavaScript, severely mitigating Cross-Site Scripting (XSS) risks.
              </p>
              <p>
                <strong>No Tracking:</strong> We do not utilize tracking pixels, third-party advertising trackers, or fingerprinting scripts. We do not sell your behavioral data.
              </p>

              <h3>3. Data Retention & Cryptographic Rotation</h3>
              <p>
                Refresh tokens are cryptographically rotated on a strict schedule. If a revoked token is ever presented to our servers, the entire token family is immediately invalidated as a protective measure against session hijacking. Your query history within the Arena is retained temporarily to maintain context during the adversarial analysis but is routinely purged from our active data stores.
              </p>

              <h3>4. Infrastructure & Hosting</h3>
              <p>
                Our backend infrastructure and databases are hosted on secured, private networks. Passwords for local authentication are hashed using Argon2, a memory-hard, GPU-resistant algorithm. We never store plaintext passwords.
              </p>

              <h3>5. Contact</h3>
              <p>
                For legal and privacy inquiries, please contact our team at <a href="mailto:hello@softagelabs.tech">hello@softagelabs.tech</a>.
              </p>
            </div>
          </TabsContent>
        </Tabs>

      </main>

      <Footer />
    </div>
  );
}
